# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qa_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10qa_service.proto\x12\nqa_service\";\n\x0fQuestionRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x16\n\x0e\x63ontext_tables\x18\x02 \x03(\t\"T\n\x0e\x41nswerResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x32\\\n\x10QuestionAnswerer\x12H\n\x0b\x41skQuestion\x12\x1b.qa_service.QuestionRequest\x1a\x1a.qa_service.AnswerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qa_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUESTIONREQUEST']._serialized_start=32
  _globals['_QUESTIONREQUEST']._serialized_end=91
  _globals['_ANSWERRESPONSE']._serialized_start=93
  _globals['_ANSWERRESPONSE']._serialized_end=177
  _globals['_QUESTIONANSWERER']._serialized_start=179
  _globals['_QUESTIONANSWERER']._serialized_end=271
# @@protoc_insertion_point(module_scope)
